# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 19:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0046_auto_20160326_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='receivers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
