#!/bin/bash
psql -qAt -d sde -c "SELECT 'ALTER '||case when c.relkind='r' then 'TABLE' else 'SEQUENCE' END||' public.'||quote_ident(relname)||' OWNER TO sde;' 
  FROM pg_class c, pg_catalog.pg_namespace n
 WHERE c.relkind IN ('r','S')
   AND c.relnamespace=n.oid
   AND n.nspname='public';" | psql -qAt -d sde

psql -qAt -d sde -c "SELECT 'GRANT SELECT ON public.'||quote_ident(relname)||' TO stationspinner;' 
  FROM pg_class c, pg_catalog.pg_namespace n
 WHERE c.relkind='r'
   AND c.relnamespace=n.oid
   AND n.nspname='public';" | psql -qAt -d sde
