#!/bin/bash
psql -d sde -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO scruffy; GRANT USAGE ON SCHEMA public TO scruffy;"
psql -d stationspinner -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO scruffy; GRANT USAGE ON SCHEMA public TO scruffy;"
