# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 19:48
from __future__ import unicode_literals

import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_capsuler_owner_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='characterIDs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='capsuler',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='capsuler',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
